### ISSUE TITLE
broken recipes

### ISSUE THREAD

**Issue by MrJorman** [Chefs-Delight/Farmersrespite-Fabric#2]
![image](https://user-images.githubusercontent.com/55187962/212934763-e2ee8550-0e50-4fe7-9fb8-9182617ff585.png)

Mod: 
Roughly Enough Items 1.19.2

**Comment by JustinPlayzz** [comment]
we are working on fixing that

**Comment by MrJorman** [comment]
No fixing.

**Comment by MrJorman** [comment]
in last version.

**Comment by MrJorman** [comment]
[2.2.0v - 1.19.2](https://www.curseforge.com/minecraft/mc-mods/farmers-respite-fabric/files/4354323)

**Comment by MrJorman** [comment]
No Fix.
![image](https://user-images.githubusercontent.com/55187962/213599374-ec75e262-4c88-4b30-a921-c4f50272aaef.png)
too problem

**Comment by JustinPlayzz** [comment]
i never said i fixed it in that version tho

**Comment by JustinPlayzz** [comment]
fixed #8

**Comment by MrJorman** [comment]
> fixed #8

download new version?

**Comment by MrJorman** [comment]
I can't find the link to the fix

**Comment by kingkuys2123** [comment]
@MrJorman, you have to wait for a while before they release the new version with the fix to CurseForge bud
