### ISSUE TITLE
[1.19.2] Brewing recipes ignore needWater in jsons?

### ISSUE THREAD

**Issue by kingkuys2123** [Chefs-Delight/Farmersrespite-Fabric#7]
Farmersrespite Fabric 2.2.0
Fabric 0.14.12
Fabric API 0.72.0
Java 8 Update 351

### Issue
All brewing recipes that have ``"needWater": false`` should'nt require water to brew them but somehow they need water to be brewed

**Comment by JustinPlayzz** [comment]
Thank you for your help :)
